Revert "WIP: remove restart step"
This reverts commit c9d1c9cd23f3387880a11ebf7f0c3cbfcd15b61d.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -49,8 +49,8 @@ jobs:
       - name: Deploy with Kustomize
         run: |
           if [ -d "kustomize/prod" ]; then
-            export IMAGE_TAG=${{ github.sha }}-${{ github.run_number }}
-            kustomize build kustomize/prod | envsubst | kubectl apply -f -
+            kustomize build kustomize/prod | kubectl apply -f -
+            kubectl rollout restart deployment/gcp-cicd -n production || echo "Deployment not found, skipping restart"
           else
             echo "Directory kustomize/prod does not exist. Skipping deployment."
           fi
